services:
  calendar-server:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - HTML_SOURCE_URL=${HTML_SOURCE_URL}
      - HOST=${HOST}
      - PORT=${PORT}
      - ROUTE_PATH=${ROUTE_PATH}
    volumes:
      - ./data:/data
    restart: always
